base_url = "https://bjornelvar.xyz"
compile_sass = true
title = "Bjössi"
description = "A clean resume theme"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "Björn Elvar"
last_name = "Þorleifsson"
address = "Reykjavík / Chicago"
email = "bjornelvar@icloud.com"
favicon = "/favicon.ico"
avatar = "/media/mois.jpg"

katex = false
show_about = true
show_skills = true
show_projects = true
show_opensource = false
show_publications = false
show_experience = true
show_education = true
show_blog = false
